# Generated by Django 5.2.3 on 2025-06-24 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=200, verbose_name='Company/Client Name')),
                ('client_reg', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('client_address', models.TextField(verbose_name='Registered Address')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('contact_position', models.CharField(max_length=100, verbose_name='Position')),
                ('contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('seta', models.CharField(choices=[('wrseta', 'WRSETA'), ('chieta', 'CHIETA'), ('bankseta', 'BANKSETA'), ('fasset', 'FASSET'), ('cftl', 'CFTL'), ('ceta', 'CETA'), ('ctfl', 'CTFL'), ('eseta', 'ESETA'), ('hwseta', 'HWSETA'), ('isett', 'ISETT'), ('inseta', 'INSETA'), ('lgseta', 'LGSETA'), ('merseta', 'MERSETA'), ('sassetta', 'SASSETA'), ('agriseta', 'AGRISETA'), ('dseta', 'DSETA'), ('theta', 'THETA'), ('teta', 'TETA')], max_length=20, verbose_name='SETA')),
                ('service', models.CharField(choices=[('wsp', 'WSP'), ('hr', 'HR'), ('both', 'Both WSP & HR')], max_length=10, verbose_name='Service Type')),
                ('sdl_number', models.CharField(max_length=50, verbose_name='SDL Number')),
                ('moderator', models.CharField(max_length=200, verbose_name='Skills Program Manager')),
                ('retainer', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monthly Retainer (R)')),
                ('payment_terms', models.CharField(choices=[('7', '7 Days'), ('15', '15 Days'), ('30', '30 Days')], default='30', max_length=10, verbose_name='Payment Terms')),
                ('qualification_type', models.CharField(choices=[('graduate', 'Graduate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('ncv', 'NCV'), ('tvet', 'TVET'), ('unemployed_learnership', 'Unemployed (Learnership)'), ('employed_learnership', 'Employed (Learnership)')], max_length=30, verbose_name='Qualification Type')),
                ('qualification_level', models.CharField(max_length=20, verbose_name='Qualification Level')),
                ('cost_per_learner', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Learner (R)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospect', 'Prospect'), ('suspended', 'Suspended')], default='prospect', max_length=20)),
                ('client_type', models.CharField(choices=[('corporate', 'Corporate'), ('individual', 'Individual'), ('government', 'Government'), ('non_profit', 'Non-Profit')], default='corporate', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('trench1', 'Trench 1'), ('trench2', 'Trench 2'), ('trench3', 'Trench 3'), ('trench4', 'Trench 4')], max_length=20, verbose_name='SLA Type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate (R)')),
                ('recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_type'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_name'], name='crm_client_client__cba63d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='crm_client_status_1220b0_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['seta'], name='crm_client_seta_1ff63f_idx'),
        ),
    ]
