# Generated by Django 5.2.3 on 2025-06-27 07:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('contact_position', models.CharField(max_length=100, verbose_name='Position')),
                ('contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('social_media', 'Social Media'), ('email', 'Email Campaign'), ('event', 'Event/Conference'), ('other', 'Other')], max_length=20, verbose_name='Lead Source')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted to Quotation'), ('lost', 'Lost'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('seta', models.CharField(blank=True, choices=[('wrseta', 'WRSETA'), ('chieta', 'CHIETA'), ('bankseta', 'BANKSETA'), ('fasset', 'FASSET'), ('cftl', 'CFTL'), ('ceta', 'CETA'), ('ctfl', 'CTFL'), ('eseta', 'ESETA'), ('hwseta', 'HWSETA'), ('isett', 'ISETT'), ('inseta', 'INSETA'), ('lgseta', 'LGSETA'), ('merseta', 'MERSETA'), ('sassetta', 'SASSETA'), ('agriseta', 'AGRISETA'), ('dseta', 'DSETA'), ('theta', 'THETA'), ('teta', 'TETA')], max_length=20, verbose_name='SETA')),
                ('service_interest', models.CharField(blank=True, choices=[('wsp', 'WSP'), ('hr', 'HR'), ('both', 'Both WSP & HR')], max_length=10, verbose_name='Service Interest')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Estimated Value (R)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('next_follow_up', models.DateTimeField(blank=True, null=True, verbose_name='Next Follow-up')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Converted At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='Quotation Number')),
                ('title', models.CharField(max_length=200, verbose_name='Quotation Title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Contract')], default='draft', max_length=20, verbose_name='Status')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Contact Person')),
                ('contact_position', models.CharField(max_length=100, verbose_name='Position')),
                ('contact_phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('seta', models.CharField(choices=[('wrseta', 'WRSETA'), ('chieta', 'CHIETA'), ('bankseta', 'BANKSETA'), ('fasset', 'FASSET'), ('cftl', 'CFTL'), ('ceta', 'CETA'), ('ctfl', 'CTFL'), ('eseta', 'ESETA'), ('hwseta', 'HWSETA'), ('isett', 'ISETT'), ('inseta', 'INSETA'), ('lgseta', 'LGSETA'), ('merseta', 'MERSETA'), ('sassetta', 'SASSETA'), ('agriseta', 'AGRISETA'), ('dseta', 'DSETA'), ('theta', 'THETA'), ('teta', 'TETA')], max_length=20, verbose_name='SETA')),
                ('service_type', models.CharField(choices=[('wsp', 'WSP'), ('hr', 'HR'), ('both', 'Both WSP & HR')], max_length=10, verbose_name='Service Type')),
                ('sdl_number', models.CharField(blank=True, max_length=50, verbose_name='SDL Number')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Value (R)')),
                ('payment_terms', models.CharField(choices=[('7', '7 Days'), ('15', '15 Days'), ('30', '30 Days')], default='30', max_length=10, verbose_name='Payment Terms')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sent Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_to_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_lead', to='crm.quotation'),
        ),
        migrations.CreateModel(
            name='QuotationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('service_type', models.CharField(choices=[('trench1', 'Trench 1'), ('trench2', 'Trench 2'), ('trench3', 'Trench 3'), ('trench4', 'Trench 4'), ('wsp', 'WSP Service'), ('hr', 'HR Service'), ('custom', 'Custom Service')], max_length=20, verbose_name='Service Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price (R)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price (R)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status'], name='crm_quotati_status_9c1f35_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='crm_quotati_quotati_243198_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['seta'], name='crm_quotati_seta_609bee_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until'], name='crm_quotati_valid_u_34b2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='crm_lead_status_2c1bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='crm_lead_source_0cf4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['seta'], name='crm_lead_seta_4ead41_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['next_follow_up'], name='crm_lead_next_fo_04fff5_idx'),
        ),
    ]
